package com.melardev.chat.net.packets;

public enum PacketType {
	PUBLIC_MESSAGE, LOGIN_REQUEST, LOGIN_RESPONSE, ANNOUNCE_DISCONNECT, ANNOUNCE, ANNOUNCE_JOIN, ANNOUNCE_BANNED, UPDATE_CONTACTS, UPDATE_CONTACTS_DISCONNECT, PRIVATE_MESSAGE, FILE_ATTACH;
}
